currentDirectory="$(cd "$(dirname "$0")" && pwd)"
. "$currentDirectory/aliases.sh"
. "$currentDirectory/security_functions.sh"
. "$currentDirectory/epi_functions.sh"
. "$currentDirectory/git_functions.sh"
